// Data shapes consumed by both PDF templates.
// Deliberately flat — assembled once by the API route, passed into the component.

export interface PDFMunicipio {
  nombre: string
  departamento?: string
  nit?: string
  representante_legal?: string
  cedula_representante?: string
}

export interface PDFPartner {
  nombre_completo: string
  cedula: string
  cargo?: string
  telefono?: string
  direccion?: string
}

export interface PDFPeriodo {
  numero: number
  mes: string
  anio: number
  fecha_inicio: string
  fecha_fin: string
  valor_cobro: number
  valor_letras?: string // "TRES MILLONES M/L" — optional, generated by backend or stored
}

export interface PDFContrato {
  numero: string
  anio: number
  objeto: string
  modalidad_seleccion: string
  valor_total: number
  valor_letras_total?: string  // "VEINTICUATRO MILLONES DE PESOS M/L"
  valor_mensual: number
  valor_letras_mensual: string // always required
  plazo_meses?: number         // e.g. 8
  duracion_letras?: string     // "OCHO" — the word for the number above
  banco: string
  tipo_cuenta: string
  numero_cuenta: string
  dependencia: string
  fecha_inicio_contrato?: string // "YYYY-MM-DD" — start of the full contract
  fecha_fin_contrato?: string    // "YYYY-MM-DD" — end of the full contract
  contratista: PDFPartner
  supervisor: PDFPartner
}

export interface PDFEvidencia {
  url: string
  nombre_archivo: string
}

export interface PDFActividad {
  descripcion: string
  cantidad: number
  evidencias: PDFEvidencia[]
}

export interface PDFObligacion {
  descripcion: string
  es_permanente: boolean
  actividades: PDFActividad[]
}

export interface PDFData {
  municipio: PDFMunicipio
  contrato: PDFContrato
  periodo: PDFPeriodo
  obligaciones: PDFObligacion[]
  fechaGeneracion: string // DD/MM/YYYY
}
